### PR TITLE
Chef 16 Compatibility Fixes

### PR DESCRIPTION
**Pull request by zimmerry**

### CODE REVIEW

**Comment by zimmerry** [comment]
[Chef 16: proxytrack](https://trello.com/c/5TnBqSRe/1975-chef-16-proxytrack)

**Review by ramereth — APPROVED** [review]
Please do a patch bump

**Comment by zimmerry** [comment]
!bump patch *

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v1.0.4.  Have a nice day!

**Pull request merged**
